### ISSUE TITLE
Array parsed as empty string

### ISSUE THREAD

**Issue by andidev** [d3x0r/JSOX#9]
Array is parsed as empty string if object has field after array
```js
const jsox = '{a:"",b:[{c:[{d:false}]}],e:"TEST"}';
console.log(JSOX.parse(jsox)); // prints { a: '', b: '', e: 'TEST' }
```

if no field is there it is parsed correctly as array
```js
const jsox2 = '{a:"",b:[{c:[{d:false}]}]}';
console.log(JSOX.parse(jsox2)); // prints { a: '', b: [ { c: [Array] } ] }
```

Using version 1.1.121 from npm.
Great work by the way! I was hoping on using this in production but I guess it is not ready for that yet?

**Comment by d3x0r** [comment]
Well that's an embarrassingly simple error :)
It was already fixed on the current git head... I had added an eslint and testing phase before publishing too... new version is 1.2.101; tagged and pushed here too.

```
const jsox = '{a:"",b:[{c:[{d:false}]}],e:"TEST"}';
console.log(JSOX.stringify(JSOX.parse(jsox))); // prints { a: '', b: '', e: 'TEST' }
{a:"",b:[{c:[{d:false}]}],e:"TEST"}

const jsox2 = '{a:"",b:[{c:[{d:false}]}]}';
console.log(JSOX.stringify(JSOX.parse(jsox2))); // prints { a: '', b: [ { c: [Array] } ] }
{a:"",b:[{c:[{d:false}]}]}
```

**Comment by d3x0r** [comment]
I did add your very own test: https://github.com/d3x0r/JSOX/blob/master/test/issue-9.js  
Although, I'm sure it was caught in porting the automated tests from JSON6 project.  I've been using this continuously for a long time, I recently started using more of the class revival features, which has revealed a few bugs in looking up references some complex and reviving typed objects.  But as just JSON without quotes, this has worked really well, and I don't actually KNOW which particular fix fixed this issue 👎 and that sort of bothers me....

**Comment by d3x0r** [comment]
I have to add just one more comment; this really has been nagging me...
I've been using the node native addon version of JSOX more... and then mostly for flat messages to the browser.  I used the native version to exchange objects between 'worker_threads' and for storing objects in object storage; the browser/client interfaces for a long time were just flat single object (single level) messages... but everything the C/JS version can do, this can also do now; none of the additional recent tests affected that version... but the C version first parses everything into a union value and then goes through those lists to build the JS objects; the JS native version builds the result as it parses, and had a little bit of split personality pushing previous contexts... and really JSON6 never would have had that issue - and this is mostly a fork of that from years ago; again, such a simple thing should not have failed.
https://www.npmjs.com/package/sack.vfs#jsox--and-json-json6----json-and-json6-compatible-processor
And I was starting to do https://github.com/d3x0r/jsox-wasm but then the interop between wasm and JS for recreating the objects was pretty slow compared to just the JS version (which apparently works just fine now, and really neither of these need to be mentioned)

**Comment by d3x0r** [comment]
Published a new version, don't fore-see any changes in the near future.  Fixed an issue parsing bigint is probably the most notable 'common' issue.  The others fixes are about user types and macro-tags.
